// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg6lefpyMf0fEYIKxkCm5S93L_axMve8g',
    appId: '1:193633746870:web:ffbde33cd35dc38e108b17',
    messagingSenderId: '193633746870',
    projectId: 'axial-paratext-445114-k2',
    authDomain: 'axial-paratext-445114-k2.firebaseapp.com',
    storageBucket: 'axial-paratext-445114-k2.firebasestorage.app',
    measurementId: 'G-2KFQRSTQZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdKdAxVhkOWdTy0X4phphzFZsRUllSUw',
    appId: '1:193633746870:android:6788674725d15e9d108b17',
    messagingSenderId: '193633746870',
    projectId: 'axial-paratext-445114-k2',
    storageBucket: 'axial-paratext-445114-k2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-zvsOsZ-sEZAxzt8m8heJMkeNP9whro',
    appId: '1:193633746870:ios:46dd59ec809b3d33108b17',
    messagingSenderId: '193633746870',
    projectId: 'axial-paratext-445114-k2',
    storageBucket: 'axial-paratext-445114-k2.firebasestorage.app',
    iosBundleId: 'com.djossimatch.djossimatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-zvsOsZ-sEZAxzt8m8heJMkeNP9whro',
    appId: '1:193633746870:ios:46dd59ec809b3d33108b17',
    messagingSenderId: '193633746870',
    projectId: 'axial-paratext-445114-k2',
    storageBucket: 'axial-paratext-445114-k2.firebasestorage.app',
    iosBundleId: 'com.djossimatch.djossimatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg6lefpyMf0fEYIKxkCm5S93L_axMve8g',
    appId: '1:193633746870:web:3c0938f897d6645b108b17',
    messagingSenderId: '193633746870',
    projectId: 'axial-paratext-445114-k2',
    authDomain: 'axial-paratext-445114-k2.firebaseapp.com',
    storageBucket: 'axial-paratext-445114-k2.firebasestorage.app',
    measurementId: 'G-MHTFWTL136',
  );
}
